version: '3.7'

services:
  postgres-13:
    image: postgres:13.6-alpine3.15
    container_name: postgres-isolation
    restart: unless-stopped
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=isolation

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus-isolation
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana-isolation
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
